<a href="https://colab.research.google.com/github/hemu2014/python-data-test/blob/main/3.%20NumPy%20exercises%E2%80%94%E2%80%94333.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# NumPy exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

2.0.2


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array creation

### Create a numpy array of size 10, filled with zeros.

In [2]:
# your code goes here
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#np.array([0] * 10)
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with values ranging from 10 to 49

In [5]:
# your code goes here
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 2*2 integers, filled with ones.

In [7]:
# your code goes here
np.ones([2, 2], dtype=np.int64)

array([[1, 1],
       [1, 1]])

In [9]:
np.ones([2,2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [10]:
# your code goes here
np.ones([3,2], dtype=np.float64)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

*已被弃用*

In [11]:
np.ones([3,2], dtype=np.float)

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [15]:
# your code goes here
X = np.arange(5, dtype=np.int64)
B = np.empty(5)
B.fill(1)
B

array([1., 1., 1., 1., 1.])

In [14]:
X = np.arange(4, dtype=np.int64)

np.ones_like(X)

array([1, 1, 1, 1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

只是具有数组矩阵的格式

In [16]:
# your code goes here
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
np.ones_like(X)

array([[1, 1, 1],
       [1, 1, 1]])

In [20]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)
np.empty_like(X)

array([[    82246787,            0, 433791697006],
       [408021893235, 450971566188, 433791697003]])

In [17]:
X = np.array([[1,2,3], [4,5,6]], dtype=np.int64)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy matrix of 4*4 integers, filled with fives.

In [21]:
# your code goes here
np.ones([4,4], dtype=np.int64) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [25]:
np.ones([2,4], dtype=np.int64, order="C") * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
np.ones([4,4], dtype=np.int) * 5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [26]:
# your code goes here
X= np.array([[2,3], [6,2]], dtype=np.int64)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [27]:
X = np.array([[2,3], [6,2]], dtype=np.int)

np.ones_like(X) * 7

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [30]:
# your code goes here
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#np.eye(3)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array, filled with 3 random integer values between 1 and 10.

In [31]:
# your code goes here
np.random.randint(10, size=5)

array([1, 4, 8, 1, 8])

In [32]:
np.random.randint(10, size=3)

array([8, 9, 8])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3\*3\*3 numpy matrix, filled with random float values.

0--1的float数据

In [34]:
# your code goes here
np.random.randn(3,3,3)

array([[[-0.26561491, -0.10937817, -0.73323603],
        [-1.38990172,  1.31995024,  1.4338098 ],
        [ 1.50884956, -0.5964876 , -0.65604007]],

       [[ 0.94574116,  0.53981234, -1.62580173],
        [-0.46209644, -0.65964587,  0.98855468],
        [ 1.03328725, -1.93595465,  0.09311671]],

       [[-1.16048857,  0.01947584, -0.54643381],
        [-1.02106713, -0.24092046,  1.58331122],
        [ 0.69709465, -1.56985695,  0.84833184]]])

In [35]:
#np.random.random((3,3,3))
np.random.randn(3,3,3) # 0 to 1 floats

array([[[-0.69956132,  0.92287117, -0.95986844],
        [-0.12237862, -0.21922355, -0.28081538],
        [ 0.22157353,  1.36553092,  0.31596709]],

       [[ 1.1397154 ,  0.66611784, -1.76792321],
        [-0.45507266,  1.22993786,  0.12828129],
        [-1.60691686, -0.9079077 , -0.60475246]],

       [[-0.7139394 , -1.29247384, -2.24216237],
        [ 0.08243266,  0.26762285, -0.85713684],
        [ 1.59959594,  0.33132819,  1.2525209 ]]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y numpy array

In [36]:
# your code goes here
X = [1,2,3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [38]:
X = [1, 2, 3]
print(X, type(X), id(X))

Y = np.array(X)
print(Y, type(Y), id(Y)) # different type

[1, 2, 3] <class 'list'> 134849106042432
[1 2 3] <class 'numpy.ndarray'> 134849105786128


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, make a copy and store it on Y.

In [39]:
# your code goes here
X = np.array([5,5,3],dtype=np.int32)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 5 3] 134849105437552
[5 5 3] 134849105435824


python中，列表赋值指向同一块内存

In [42]:
X = np.array([5,5,3],dtype=np.int32)
print(X, id(X))

Y = X
print(Y, id(Y))

[5 5 3] 134849105437456
[5 5 3] 134849105437456


In [43]:
X = [1,2,3,23]
print(X, id(X))

Y = X
print(Y, id(Y))

Z = [1,2,3,23]
print(Z, id(Z))

[1, 2, 3, 23] 134849105379200
[1, 2, 3, 23] 134849105379200
[1, 2, 3, 23] 134849105575424


In [41]:
X = np.array([5,2,3], dtype=np.int64)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 134849105786128
[5 2 3] 134849105437936


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10

不包括终点

In [44]:
# your code goes here
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with the odd numbers between 1 to 10

起点，终点，步长

In [48]:
# your code goes here
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [47]:
np.arange(1, 11, 3)

array([ 1,  4,  7, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a numpy array with numbers from 1 to 10, in descending order.

In [55]:
# your code goes here
a = np.arange(10, 0, -1)
print(a)

[10  9  8  7  6  5  4  3  2  1]


In [56]:
np.flip(np.arange(1,11))

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [57]:
np.sort(np.arange(1,11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [58]:
# your code goes here
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
new_var = np.arange(10).reshape(2,5)
new_var

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

数据个数需对应

In [64]:
np.arange(10).reshape(2,4)

ValueError: cannot reshape array of size 10 into shape (2,4)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Show the memory size of the given Z numpy matrix

每个元素的大小， 数据的个数

In [67]:
# your code goes here
a = np.zeros((10,10))
print(f'{a}, bytes: {a.size}, {a.size * a.itemsize}')

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], bytes: 100, 800


In [68]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [71]:
a = 1
b = 1
c = 3
print("%d-%d-%d" % (a,b,c))

1-1-3


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array indexation


### Given the X numpy array, show it's first element

In [73]:
# your code goes here
X = np.array(['a', 'b', 'c', 'd', 'e'])
X[3]

np.str_('d')

In [74]:
X = np.array(['A','B','C','D','E'])

X[0]

np.str_('A')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's last element

通过下标索引来查询数据

In [77]:
# your code goes here
a = np.array(['a', 'b', 'c', 'd', 'e'])
print(a[-1])
a[len(a) -1]

e


np.str_('e')

In [78]:
X = np.array(['A','B','C','D','E'])

#X[len(X)-1]
X[-1]

np.str_('E')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show it's first three elements

通过切片操作进行取值

In [79]:
# your code goes here
a = np.array(['a', 'b', 'c', 'd', 'e'])
a[:3]

array(['a', 'b', 'c'], dtype='<U1')

In [80]:
X = np.array(['A','B','C','D','E'])

X[0:3] # remember! elements start at zero index

array(['A', 'B', 'C'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show all middle elements

排除前后两个数，从下标1开始取，到最后一个结束，不包括终点

---



In [86]:
# your code goes here
a = np.array(['a', 'b', 'c', 'd', 'e'])
a[1:-1]
print(a[1:len(a) -1])

['b' 'c' 'd']


In [82]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in reverse position

In [87]:
# your code goes here
a = np.array(['a', 'b', 'c', 'd', 'e'])
a[::-1]

array(['e', 'd', 'c', 'b', 'a'], dtype='<U1')

In [88]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the elements in an odd position

In [89]:
# your code goes here
a = np.array(['a', 'b', 'c', 'd', 'e'])
a[::2]

array(['a', 'c', 'e'], dtype='<U1')

通过下标索引查询数值

In [90]:
a = np.array(['a', 'b', 'c', 'd', 'e'])
a[[0, 2, -1]]

array(['a', 'c', 'e'], dtype='<U1')

In [91]:
X = np.array(['A','B','C','D','E'])

#X[[0, 2, -1]]
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first row elements

a[[0,1,-1], [0,1,3]],第一个列表参数取相应的行数据，第一个列表参数是每一行取数据的索引，每行只取一个数据，要去多个数据可以使用切片操作

In [102]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(a[[0, -1], :2])
print("-----")
print(a[[0,1,-1], [0,1,3]])
print(a[:, -1:1:-1])

[[ 1  2]
 [13 14]]
-----
[ 1  6 16]
[[ 4  3]
 [ 8  7]
 [12 11]
 [16 15]]


In [93]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last row elements

In [106]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
a[-1]
print(a[len(a[0])-1])

[13 14 15 16]


In [104]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first element on first row

In [107]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(a[1][3])
print(a[1, 3])

8
8


In [108]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

np.int64(1)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last element on last row

In [109]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
a[-1][-1]

np.int64(16)

把它当做是python中的列表操作

In [110]:
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
a[-1, -1]

np.int64(16)

In [111]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[-1][-1]
X[-1, -1]

np.int64(16)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the middle row elements

In [115]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(a.shape)
print(a[1:a.shape[0] - 1, 1:a.shape[1] - 1])

(4, 4)
[[ 6  7]
 [10 11]]


In [116]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the first two elements on the first two rows

In [117]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
a[:2, :2]

array([[1, 2],
       [5, 6]])

In [118]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[:2][:2] wrong!
#X[0:2, 0:2]
X[:2, :2]

array([[1, 2],
       [5, 6]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the last two elements on the last two rows

In [126]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
print(a.shape)
print(a[a.shape[0] - 2:, a.shape[1] - 2:])
print("----")
print(a[-2:, -2:])

(4, 4)
[[11 12]
 [15 16]]
----
[[11 12]
 [15 16]]


In [121]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Array manipulation


### Convert the given integer numpy array to float

In [127]:
# your code goes here
a = [-5, -3, 0, 10, 40]
np.array(a, np.float64)

array([-5., -3.,  0., 10., 40.])

In [128]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float32)

array([-5., -3.,  0., 10., 40.], dtype=float32)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given numpy array (first element becomes last)

In [129]:
# your code goes here
a = [-5, -3, 0, 10, 40]
a[::-1]

[40, 10, 0, -3, -5]

In [130]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given numpy array

In [132]:
# your code goes here
a = [0, 10, -5, 40, -3, -1, 0, 0]

a.sort()
a

[-5, -3, -1, 0, 0, 0, 10, 40]

In [131]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, set the fifth element equal to 1

In [136]:
# your code goes here
x = np.arange(10)
x
print(x, x[4])
x[4] = 3
print(x, x[4])

[0 1 2 3 4 5 6 7 8 9] 4
[0 1 2 3 3 5 6 7 8 9] 3


In [137]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, change the 50 with a 40

可以添加条件查询特定的值

In [141]:
# your code goes here
a = np.array([10, 20, 30, 50, 33])

a[a == 33] = 40
a

array([10, 20, 30, 50, 40])

In [139]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last row with all 1

In [142]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1].fill(1)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [153]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.ones(4)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [143]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, change the last item on the last row with a 0

In [151]:
# your code goes here
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1].fill(0)
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [156]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = np.zeros(1)
X

<ipython-input-156-d18280fadbc9>:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  X[-1, -1] = np.zeros(1)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

In [149]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, add 5 to every element

In [157]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
a + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [158]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Boolean arrays _(also called masks)_


### Given the X numpy array, make a mask showing negative elements

X < 0,条件语句会返回一个布尔数组，在通过类似a[ 条件 ]，取对应的True元素

In [161]:
# your code goes here
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X < 0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

In [160]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get the negative elements

In [162]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X[X < 0]

array([-1, -4, -9])

In [163]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X <= 0
X[mask]

array([-1,  0, -4,  0,  0, -9])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than 5

In [165]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 3
print(X[mask], X[X > 5])

[ 5  6 10] [ 6 10]


In [166]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers higher than the elements mean

In [177]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()

print(X[mask], X[X > X.mean()], np.median(X), X[X > np.median(X)], X.mean())
print(X[X > np.median(X)])

[ 2  5  6 10] [ 2  5  6 10] 0.0 [ 2  5  6 10] 0.9
[ 2  5  6 10]


In [176]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, get numbers equal to 2 or 10

In [178]:
# your code goes here
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
print(X[mask], X[(X == 2) | (X == 10)])

[ 2 10] [ 2 10]


In [179]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions


### Given the X numpy array, return True if none of its elements is zero

所有的值都不能为0

In [180]:
# your code goes here
a = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

a.all()

np.False_

In [181]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.all()

np.False_

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, return True if any of its elements is zero

只要一个为真就返回true

In [184]:
# your code goes here
X = np.array([ 0, 0, 0, 0])

X.any()

np.False_

In [185]:
X = np.array([ 1, 0, 0, 0])

X.any()

np.True_

In [183]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

X.any()

np.True_

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X numpy array, show the sum of its elements

In [186]:
# your code goes here
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
print(X.sum(), np.sum(X))

43 43


In [187]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])

#np.sum(X)
X.sum()

np.int64(43)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the mean value of its elements

In [189]:
# your code goes here
a = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
print(a.mean(), np.mean(a))

3.7 3.7


In [190]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.mean(X)
X.mean()

np.float64(3.7)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the sum of its columns

axis为0： 列， axis 1: 行

In [192]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

a.sum(axis=1) # remember: axis=0 columns; axis=1 rows

array([10, 26, 42, 58])

In [193]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0) # remember: axis=0 columns; axis=1 rows

array([28, 32, 36, 40])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy matrix, show the mean value of its rows

In [196]:
# your code goes here
a = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

a.mean(axis=0) # remember: axis=0 columns; axis=1 rows

array([ 7.,  8.,  9., 10.])

In [195]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) # remember: axis=0 columns; axis=1 rows

array([ 2.5,  6.5, 10.5, 14.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X numpy array, show the max value of its elements

In [202]:
# your code goes here
a = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
print(a.max(), a.min(), "min")
print(np.max(a), np.min(a), "max")
print(np.sort(a))
print("---")
print(np.percentile(a, 75), "percentile75")
print(np.percentile(a, 50), "percentile50")
print(np.percentile(a, 25), "percentile25")
print(np.median(a), "median")
print(np.std(a), a.std(), "std")
print(np.var(a), a.var(), "var")

10 0 min
10 0 max
[ 0  0  0  1  2  4  5  6  9 10]
---
5.75 percentile75
3.0 percentile50
0.25 percentile25
3.0 median
3.5510561809129406 3.5510561809129406 std
12.61 12.61 var


In [200]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])

#np.max(X)
X.max()

np.int64(10)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)